// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/degary/goframe-shop/internal/logic/position"
	_ "github.com/degary/goframe-shop/internal/logic/rotation"
)
