# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name:     "shop"
    arch:     "arm64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link:            "mysql:root:123456@tcp(10.8.10.83:23306)/gorm-shop"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true