// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/degary/goframe-shop/internal/model"
)

type (
	IPosition interface {
		Add(ctx context.Context, in model.PositionAddInput) (out model.PositionAddOutput, err error)
		Delete(ctx context.Context, id int) error
		Update(ctx context.Context, in model.PositionUpdateInput) error
		GetList(ctx context.Context, in model.PositionGetListInput) (out *model.PositionGetListOutput, err error)
	}
)

var (
	localPosition IPosition
)

func Position() IPosition {
	if localPosition == nil {
		panic("implement not found for interface IPosition, forgot register?")
	}
	return localPosition
}

func RegisterPosition(i IPosition) {
	localPosition = i
}
